/**
 * Sentinel SDK — Protocol Types
 *
 * Types for the v3 node protocol: node status, handshakes,
 * WireGuard tunnels, V2Ray configs, and transport rates.
 *
 * v3 differences from v2:
 * - Node status: GET / (not GET /status)
 * - Handshake: POST / (not POST /accounts/{addr}/sessions/{id})
 * - field: service_type (not type), remote_addrs (array, not remote_url string)
 * - Sessions wrapped in base_session
 */

/// <reference types="node" />

// ─── Node Status ───────────────────────────────────────────────────────────

/** Normalized node status from nodeStatusV3(). Combines v3 API response fields. */
export interface NodeStatus {
  /** sentnode1... address (may be empty if node doesn't report it) */
  address: string;
  /** Service type: 'wireguard' or 'v2ray' */
  type: 'wireguard' | 'v2ray';
  /** Node display name */
  moniker: string;
  /** Current peer count (active connections) */
  peers: number;
  /** Bandwidth capabilities */
  bandwidth: {
    /** Download speed in bytes/s */
    download: number;
    /** Upload speed in bytes/s */
    upload: number;
  };
  /** Geographic location */
  location: {
    /** City name */
    city: string;
    /** Country name (as reported by node -- may be variant like "Turkiye") */
    country: string;
    /** ISO 3166-1 alpha-2 country code (as reported by node) */
    country_code: string;
    /** Latitude */
    latitude: number;
    /** Longitude */
    longitude: number;
  };
  /** Quality of service limits */
  qos: {
    /** Maximum allowed peers (null if not configured) */
    max_peers: number | null;
  };
  /**
   * Clock drift in seconds between our machine and the node.
   * Positive = node clock is ahead. null = couldn't determine.
   * VMess AEAD fails if |drift| > 120s.
   */
  clockDriftSec: number | null;
  /** Per-GB pricing (empty array -- not in v3 status, fetched from LCD) */
  gigabyte_prices: unknown[];
  /** Raw response object from node API */
  _raw: unknown;
}

// ─── WireGuard ─────────────────────────────────────────────────────────────

/** WireGuard Curve25519 key pair from generateWgKeyPair(). */
export interface WgKeyPair {
  /** Private key (32 bytes, bit-clamped per WG spec) */
  privateKey: Buffer;
  /** Public key (32 bytes, X25519 base point multiplication) */
  publicKey: Buffer;
}

/** WireGuard configuration parameters for writeWgConfig(). */
export interface WgConfigOptions {
  /**
   * DNS servers as comma-separated string.
   * Default: Handshake DNS with Google/Cloudflare fallbacks.
   */
  dns?: string;
  /**
   * MTU value. Sentinel nodes use 1280.
   * Higher values may cause packet fragmentation issues.
   */
  mtu?: number;
  /**
   * Keepalive interval in seconds (default: 15).
   * Prevents NAT timeout on residential connections.
   */
  keepalive?: number;
}

// ─── Handshake Results ─────────────────────────────────────────────────────

/**
 * Result from WireGuard handshake (initHandshakeV3).
 * Contains everything needed to configure the WG interface.
 */
export interface HandshakeResult {
  /** IP addresses assigned to our WireGuard interface (e.g. ['10.8.0.2/32']) */
  assignedAddrs: string[];
  /** Server's WireGuard public key (base64-encoded) */
  serverPubKey: string;
  /** Server's WireGuard endpoint (e.g. '185.47.255.36:52618') */
  serverEndpoint: string;
  /** Raw JSON config string from node response */
  config: string;
  /** Full handshake response object */
  result: unknown;
}

/**
 * Result from V2Ray handshake (initHandshakeV3V2Ray).
 * Contains metadata for building the V2Ray client config.
 */
export interface V2RayHandshakeResult {
  /**
   * JSON string of V2Ray metadata.
   * Pass this to buildV2RayClientConfig() as the metadataJson parameter.
   * Contains: transport type, port, service name, security settings.
   */
  config: string;
  /** Full handshake response object */
  result: unknown;
}

// ─── V2Ray Config ──────────────────────────────────────────────────────────

/** Options for buildV2RayClientConfig(). */
export interface V2RayConfigOptions {
  /** DNS servers (comma-separated or preset name) */
  dns?: string;
  /** DNS preset name ('handshake', 'google', 'cloudflare') */
  dnsPreset?: string;
}

/**
 * V2Ray client configuration object (JSON structure).
 * Generated by buildV2RayClientConfig(). Write this to a JSON file
 * and pass to v2ray.exe as the config argument.
 */
export interface V2RayConfig {
  /** Log configuration */
  log: { loglevel: string };
  /** Inbound proxy configuration (SOCKS5) */
  inbounds: Array<{
    tag: string;
    protocol: string;
    listen: string;
    port: number;
    settings: { auth: string; udp: boolean };
  }>;
  /** Outbound configurations (one per transport/metadata entry) */
  outbounds: Array<{
    tag: string;
    protocol: string;
    settings: {
      vnext?: Array<{
        address: string;
        port: number;
        users: Array<{
          id?: string;
          uuid?: string;
          encryption?: string;
          alterId?: number;
          security?: string;
        }>;
      }>;
    };
    streamSettings?: {
      network: string;
      security: string;
      tlsSettings?: Record<string, unknown>;
      grpcSettings?: Record<string, unknown>;
      wsSettings?: Record<string, unknown>;
      httpSettings?: Record<string, unknown>;
      tcpSettings?: Record<string, unknown>;
      kcpSettings?: Record<string, unknown>;
      quicSettings?: Record<string, unknown>;
    };
  }>;
  /** Routing rules (balancer, direct, DNS) */
  routing?: {
    domainStrategy: string;
    rules: Array<Record<string, unknown>>;
    balancers?: Array<Record<string, unknown>>;
  };
  /** DNS configuration */
  dns?: { servers: string[] };
  /** Observatory for active probing */
  observatory?: Record<string, unknown>;
}

// ─── Transport Rates ───────────────────────────────────────────────────────

/** Static transport success rate (from 780-node scan). */
export interface TransportSuccessRate {
  /** Success rate 0.0-1.0 */
  rate: number;
  /** Number of nodes tested */
  sample: number;
  /** Human-readable note about this transport */
  note: string;
}

/** Dynamic transport rate (runtime tracking, persisted to disk). */
export interface DynamicTransportRate {
  /** Success rate 0.0-1.0 */
  rate: number;
  /** Total samples (success + fail) */
  sample: number;
}

// ─── Speed Testing ─────────────────────────────────────────────────────────

/** Speed test result from speedtestDirect() or speedtestViaSocks5(). */
export interface SpeedResult {
  /** Download speed in Mbps */
  mbps: number;
  /** Number of chunks downloaded */
  chunks: number;
  /** Adaptive strategy used (e.g. 'full', 'probe-only') */
  adaptive: string;
  /** Total bytes downloaded */
  totalBytes?: number;
  /** Test duration in seconds */
  seconds?: number;
  /** Fallback host used (if primary failed) */
  fallbackHost?: string;
}

/** Speed test comparison from compareSpeedTests(). */
export interface SpeedComparison {
  /** True if after test is faster */
  improved: boolean;
  /** True if after test is slower */
  degraded: boolean;
  /** Raw delta values */
  delta: {
    downloadMbps: number;
    uploadMbps: number;
    latencyMs: number;
  };
  /** Percentage change */
  percentChange: {
    download: number;
    upload: number;
  };
}

/** Speed test configuration constants. */
export interface SpeedtestDefaults {
  /** Bytes per chunk for download test */
  readonly chunkBytes: number;
  /** Number of chunks to download */
  readonly chunkCount: number;
  /** Bytes for initial probe */
  readonly probeBytes: number;
  /** Mbps threshold for full test vs probe-only */
  readonly probeThresholdMbps: number;
  /** Primary speed test host */
  readonly primaryHost: string;
  /** DNS cache TTL in ms */
  readonly dnsCacheTtl: number;
  /** Fallback speed test hosts */
  readonly fallbackHosts: ReadonlyArray<{
    host: string;
    path: string;
    size: number;
  }>;
}

// ─── WireGuard Tunnel Management ───────────────────────────────────────────

/** Result from watchdogCheck() -- quick tunnel health check. */
export interface WatchdogResult {
  /** Whether a tunnel is currently active */
  active: boolean;
  /** Tunnel name (e.g. 'sentinel0') */
  name?: string;
  /** Tunnel uptime in ms */
  uptimeMs?: number;
}

/** Result from checkOrphanedTunnels(). */
export interface OrphanedTunnelCheck {
  /** Whether orphaned tunnels were found */
  found: boolean;
  /** Names of orphaned tunnels */
  tunnels: string[];
  /** Whether cleanup was performed */
  cleaned: boolean;
}

/** Result from cleanOrphanedTunnels(). */
export interface CleanOrphanedResult {
  /** Number of tunnels cleaned */
  cleaned: number;
  /** Error messages for tunnels that couldn't be cleaned */
  errors: string[];
}

/** Result from checkOrphanedV2Ray(). */
export interface OrphanedV2RayCheck {
  /** Whether orphaned V2Ray processes were found */
  found: boolean;
  /** PIDs of orphaned processes */
  pids: number[];
}

/** Result from checkVpnConflicts(). */
export interface VpnConflictCheck {
  /** Detected VPN software that may conflict */
  conflicts: Array<{
    /** VPN software name */
    name: string;
    /** Whether it's currently running */
    running: boolean;
  }>;
}

/** Result from checkPortConflicts(). */
export interface PortConflictCheck {
  /** Ports that are in use */
  conflicts: Array<{
    /** Port number */
    port: number;
    /** Whether the port is currently in use */
    inUse: boolean;
  }>;
}
